const hut_settings = [
  {
    id: 'lap_fc_hut_1',
    title: 'Hut 1',
    disabled: false,
    time: 10,
    staff: '',
    mode: 'a',
  },
  {
    id: 'lap_fc_hut_2',
    title: 'Hut 2',
    disabled: false,
    time: 10,
    staff: '',
    mode: 'a',
  },
  {
    id: 'lap_fc_hut_3',
    title: 'Hut 3',
    disabled: false,
    time: 10,
    staff: '',
    mode: 'a',
  },
  {
    id: 'lap_fc_hut_4',
    title: 'Hut 4',
    disabled: false,
    time: 10,
    staff: '',
    mode: 'a',
  },
  {
    id: 'lap_fc_hut_5',
    title: 'Hut 5 - Wheelchair',
    disabled: false,
    time: 10,
    staff: '',
    mode: 'a',
  },
  {
    id: 'lap_fc_hut_6',
    title: 'Hut 6 - Wheelchair/VIP',
    disabled: false,
    time: 10,
    staff: '',
    mode: 'a',
  },
  {
    id: 'lap_fc_hut_7',
    title: 'Hut 7 - VIP',
    disabled: false,
    time: 10,
    staff: '',
    mode: 'a',
  },
  {
    id: 'lap_fc_hut_8',
    title: 'Hut 8',
    disabled: false,
    time: 10,
    staff: '',
    mode: 'a',
  },
  {
    id: 'lap_fc_hut_9',
    title: 'Hut 9',
    disabled: false,
    time: 10,
    staff: '',
    mode: 'a',
  },
  {
    id: 'lap_fc_hut_10',
    title: 'Hut 10',
    disabled: false,
    time: 10,
    staff: '',
    mode: 'a',
  },
  {
    id: 'lap_fc_hut_11',
    title: 'Hut 11',
    disabled: false,
    time: 10,
    staff: '',
    mode: 'a',
  },
  {
    id: 'lap_fc_hut_12',
    title: 'Hut 12',
    disabled: false,
    time: 10,
    staff: '',
    mode: 'a',
  },
  {
    id: 'lap_fc_hut_13',
    title: 'Hut 13',
    disabled: false,
    time: 10,
    staff: '',
    mode: 'a',
  },
  {
    id: 'lap_fc_hut_14',
    title: 'Hut 14',
    disabled: false,
    time: 10,
    staff: '',
    mode: 'a',
  },
  {
    id: 'lap_fc_hut_15',
    title: 'Hut 15',
    disabled: false,
    time: 10,
    staff: '',
    mode: 'a',
  },
  {
    id: 'lap_fc_hut_16',
    title: 'Hut 16',
    disabled: false,
    time: 10,
    staff: '',
    mode: 'a',
  },
]

export default hut_settings
