name: Forsea Cypress Tests

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install dependencies
      run: npm install

    - name: Run Cypress tests
      run: npx cypress-tags run -e TAGS='@automated' --headless
      env:
        CYPRESS_baseUrl: https://forsea-int.b2c.ticknovate-uat.com
        CYPRESS_username: ${{ secrets.CYPRESS_USERNAME }}
        CYPRESS_password: ${{ secrets.CYPRESS_PASSWORD }}
